# Generated by Django 3.2 on 2021-04-26 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='email',
            field=models.EmailField(max_length=100),
        ),
        migrations.AlterField(
            model_name='students',
            name='l_name',
            field=models.CharField(max_length=100),
        ),
    ]
